# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Test Site
email: ti3r.bubblenet@gmail.com
description: > # Alexandro Blanco's personal website to show resume and skills
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ti3r.github.io" # the base hostname & protocol for your site
github_username:  ti3r

# Build settings
markdown: kramdown

destination: dist


webrick:
  headers:
      X-ti3r-application-id: simple-jekyll-test